services:
  postgres:
    image: postgres:16
    container_name: credit_risk_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d credit_risk"]
      interval: 5s
      retries: 5
  app:
    build: .
    container_name: credit_risk_app
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "python src/connection.py && python src/project.py"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
