services:
  postgres:
    image: postgres:16
    container_name: credit_risk_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d credit_risk"]
      interval: 5s
      retries: 5
  app:
    build: .
    container_name: credit_risk_app
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    command: "python src/project.py"

  db-init:
    image: postgres:16
    container_name: credit_risk_db_init
    env_file:
      - .env
    volumes:
      - ./sql:/sql
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_cojmpleted_successfully
    command: >
      sh -c "PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -f /sql/init.sql"
    restart: "no"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
      app:
        condition: service_completed_successfully
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
