-- auto generated raw_loans table with zero entries, to be populated by the data pipeline
CREATE TABLE IF NOT EXISTS accepted_loans (
    loan_status             TEXT,
    issue_d                 TEXT,
    id                      TEXT,
    loan_amnt               TEXT,
    term                    TEXT,
    int_rate                TEXT,
    installment             TEXT,
    grade                   TEXT,
    sub_grade               TEXT,
    emp_length              TEXT,
    home_ownership          TEXT,
    annual_inc              TEXT,
    verification_status     TEXT,
    purpose                 TEXT,
    addr_state              TEXT,
    dti                     TEXT,
    fico_range_low          TEXT,
    fico_range_high         TEXT,
    deling_2yrs             TEXT,
    inq_last_6mths          TEXT,
    open_acc                TEXT,
    pub_rec                 TEXT,
    revol_bal               TEXT,
    total_rev_hi_lim        TEXT,
    revol_util              TEXT,
    total_acc               TEXT,
    mort_acc                TEXT,
    pub_ec_bankruptcies     TEXT,
    tax_liens               TEXT,
    earliest_cr_line        TEXT,
);
