/*auto generated raw_loans table with zero entries, to be populated by the data pipeline*/
CREATE TABLE IF NOT EXISTS accepted_loans (
    loan_status             SMALLINT,
    issue_d                 DATE,
    id                      NUMERIC,
    loan_amnt               NUMERIC,
    term                    INTEGER,
    int_rate                NUMERIC,
    installment             NUMERIC,
    grade                   TEXT,
    sub_grade               TEXT,
    emp_length              INTEGER,
    home_ownership          TEXT,
    annual_inc              NUMERIC,
    verification_status     TEXT,
    purpose                 TEXT,
    addr_state              TEXT,
    dti                     NUMERIC,
    fico_range_low          NUMERIC,
    fico_range_high         NUMERIC,
    delinq_2yrs             NUMERIC,
    inq_last_6mths          NUMERIC,
    open_acc                NUMERIC,
    pub_rec                 NUMERIC,
    revol_bal               NUMERIC,
    total_rev_hi_lim        NUMERIC,
    revol_util              NUMERIC,
    total_acc               NUMERIC,
    mort_acc                NUMERIC,
    pub_rec_bankruptcies     NUMERIC,
    tax_liens               NUMERIC,
    earliest_cr_line                    DATE,
    credit_utilization                  NUMERIC,
    months_since_earliest_credit_line   INTEGER
);
